source 'https://rubygems.org'

gem "awesome_print"
gem "faker"
gem "faye-websocket"
gem "mimemagic"
gem "minitest"
gem "pbkdf2-ruby"
gem "pry"
gem "pry-rescue"
gem "pry-stack_explorer"
gem "rest-client"
gem "uuid"
