name: Lint go
on:
  push:
    branches:
      - master
    paths:
      - '.golangci.yaml'
      - '.golangci-lint-version'
      - 'Makefile'
      - '**.go'
  pull_request:
    paths:
      - '.golangci.yaml'
      - '.golangci-lint-version'
      - 'Makefile'
      - '**.go'
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          # maximum supported version
          go-version: "1.26.x"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version-file: .golangci-lint-version
          args: ./...
