name: Lint js
on:
  push:
    branches:
      - master
    paths:
      - '**.js'
  pull_request:
    paths:
      - '**.js'
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Yarn install
        run: |
          cd ./scripts
          yarn install
      - name: Run eslint
        run: make jslint
