name: Lint js
on:
  push:
    branches:
      - master
    paths:
      - '**.js'
  pull_request:
    paths:
      - '**.js'
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Yarn install 
        run: |
          cd ./scripts
          yarn install
      - uses: sibiraj-s/action-eslint@v3
        with:
          eslint-args: '--config scripts/eslintrc.json --ignore-path=.gitignore --quiet'
          extensions: 'js,jsx,ts,tsx'
          bin-path: 'scripts/node_modules/eslint/bin'
          annotations: true
