name: Create releases
on:
  push:
    tags:
      - "*.*.*" # Matching a version number like 1.4.19
jobs:
  publish_on_release:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build the binaries
        run: |
          GOOS=linux   GOARCH=amd64 ./scripts/build.sh release
          GOOS=linux   GOARCH=arm   ./scripts/build.sh release
          GOOS=freebsd GOARCH=amd64 ./scripts/build.sh release
      - name: Create the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF##*/}"
          gh release create "$tag_name" cozy-stack-* --target "$GITHUB_SHA"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
      - name: Build and publish the cozy-app-dev image
        run: scripts/release.sh
  build_deb_packages:
    strategy:
      matrix:
        os:
          [
            "debian:10",
            "debian:11",
            "debian:12",
            "ubuntu:20.04",
            "ubuntu:22.04",
          ]
    runs-on: ubuntu-latest
    needs: publish_on_release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build package
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ matrix.os }}
          options: -v ${{ github.workspace }}:/build -e GOVERSION=1.21.3
          run: |
            echo "[safe]" > /root/.gitconfig
            echo "        directory = /build" >> /root/.gitconfig
            cd /build
            scripts/packaging/installrequirements.sh
            scripts/packaging/buildpackage.sh
      - name: Upload package to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF##*/}"
          gh release upload "$tag_name" packages/*.deb
