name: Create releases
on:
  push:
    tags:
    - '*.*.*' # Matching a version number like 1.4.19
jobs:
  publish_on_release:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Check code
        uses: actions/checkout@v2
      - name: Build the binaries
        run: |
          GOOS=linux   GOARCH=amd64 ./scripts/build.sh release
          GOOS=linux   GOARCH=arm   ./scripts/build.sh release
          GOOS=freebsd GOARCH=amd64 ./scripts/build.sh release
      - name: Create the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF##*/}"
          gh release create "$tag_name" cozy-stack-* --target "$GITHUB_SHA"
